import {
  Bell,
  Bot,
  Clock,
  Code2,
  GitBranch,
  Globe,
  Mail,
  MessageCircle,
  Repeat,
  Ticket,
  UserCheck,
  Users,
  UserCog,
  Webhook,
  Zap,
} from "lucide-react";
import type { WorkflowNodeType } from "@/types";

export const NODE_ICON: Record<WorkflowNodeType, typeof Zap> = {
  trigger: Zap,
  ai_agent: Bot,
  condition: GitBranch,
  branch: GitBranch,
  api_call: Globe,
  send_email: Mail,
  send_message: MessageCircle,
  create_ticket: Ticket,
  update_customer: UserCog,
  assign_team: Users,
  human_approval: UserCheck,
  delay: Clock,
  loop: Repeat,
  webhook: Webhook,
  code: Code2,
  notification: Bell,
};

export const NODE_TYPE_LABEL: Record<WorkflowNodeType, string> = {
  trigger: "Gatilho",
  ai_agent: "Agente de IA",
  condition: "Condição",
  branch: "Ramificação",
  api_call: "Chamada de API",
  send_email: "Enviar e-mail",
  send_message: "Enviar mensagem",
  create_ticket: "Criar ticket",
  update_customer: "Atualizar cliente",
  assign_team: "Atribuir time",
  human_approval: "Aprovação humana",
  delay: "Atraso",
  loop: "Loop",
  webhook: "Webhook",
  code: "Código",
  notification: "Notificação",
};
